inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
