services:
  ynym-portal-gateway:
    image: steveltn/https-portal:1.24.0
    container_name: ynym-portal-gateway
    hostname: ynym-portal-gateway
    restart: always
    environment:
      # - STAGE=production
      - DOMAINS=api-portal.uryonym.com -> http://ynym-portal-backend:3000
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ynym-portal-backend
    volumes:
      - ynym-portal-gateway-volume:/var/lib/https-portal

  ynym-portal-backend:
    build: .
    image: ynym-portal-backend
    container_name: ynym-portal-backend
    hostname: ynym-portal-backend
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - RAILS_ENV=production
      - SECRET_KEY_BASE=1b5aec3f3ed8d557041d436ad3d4c8b31f0d9d6f66e4dcfa77b6a20b2a59e689533c8099389506b1a372ecbac7a1ba1589a76477c1a47b67cf770f33ff22656e
    volumes:
      - ./log:/app/log

volumes:
  ynym-portal-gateway-volume:
    name: ynym-portal-gateway-volume
    driver: local

networks:
  default:
    name: ynym-portal-network
    external: true
