name: "ynym-portal-backend"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Tokyo
      - RAILS_ENV=development
    volumes:
      - ../..:/workspaces:cachd

networks:
  default:
    name: develop-network
    external: true
